### ISSUE TITLE
Your domain won't resolve

### ISSUE THREAD

**Issue by theabhinavdas** [tanepiper/obsidian-garden#3]
It finally gets redirected to `http://ww1.obsidian.garden/` which I'm assuming isn't the intended behavior.

**Comment by tanepiper** [comment]
Yes, with the cost of hosting it on Obsidian and the cost of the tld, I let it go as it's not an active project.

**Comment by theabhinavdas** [comment]
In that case, you might want to not link to it from Github etc? Not sure. I think users of this project might be able to support some costs.

**Comment by tanepiper** [comment]
Thanks, I've removed it - this was only a side project and was given away for free. I'd never asked anyone to fund it, but I also don't have any duty to continue with it either.

**Comment by theabhinavdas** [comment]
Gotcha. I'm using it currently, and it is helping me a lot. Thank you for sharing this :)
